---

- name: Install rpmfusion repos
  dnf:
    name: "{{ rpm_fusion_repos }}"
    state: present
    disable_gpg_check: yes
  become: true

- name: Install required packages
  dnf:
    name: "{{ required_packages }}"
    state: latest
  when: required_packages is defined
  become: true

- name: Check if PostgreSQL database is initialized.
  stat:
    path: "{{ postgresql_data_dir }}/PG_VERSION"
  register: pgdata_dir_version
  become: true
