- name: kill elementary appcenter
  command: pkill -f io.elementary.appcenter
  ignore_errors: true

- name: update and upgrade system packages
  apt:
    update_cache: yes
    upgrade: full
  become: true

- name: install required packages
  apt:
    name: "{{ required_packages }}"
    state: latest
    autoremove: yes
    update_cache: yes
  when: required_packages is defined
  become: true

- name: ensure iio-sensor-proxy removed
  apt:
    name: iio-sensor-proxy
    state: absent
    autoremove: yes
    purge: yes
  become: true
  when: ansible_distribution_version == "19.10"

- name: Stupid touchpad fix
  ansible.builtin.file:
    src: restart-touchpad
    dest: /lib/systemd/system-sleep/restart-touchpad
    mode: '0755'
    owner: root
    group: root
  become: true
  when: ansible_distribution_version == "24.04"
