---
- name: Ubuntu | Install
  block:
  - name: Install dependencies
    apt:
      name: "{{ ubuntu_dependencies }}"
      state: present
    become: true

  - name: Install keyring
    shell: |
      set -o pipefail
      curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft.gpg
    args:
      creates: /usr/share/keyrings/microsoft.gpg
    become: true

  - name: Install VS Code repo
    become: true
    apt_repository:
      repo: deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main
      filename: vscode
      state: present

  - name: Install VS Code
    become: true
    apt:
      name: "code{{ (visual_studio_code_version != '') | ternary('=' + visual_studio_code_version, '') }}"
      state: present
  when: ansible_distribution in ["Ubuntu", "Pop!_OS"]

- name: Fedora | Install
  block:
  - name: Install dependencies
    dnf:
      name: "{{ fedora_dependencies }}"
      state: present
    become: true

  - name: Install VS Code repo
    yum_repository:
      name: Code
      description: Visual Studio Code Repo
      baseurl: https://packages.microsoft.com/yumrepos/vscode
      enabled: yes
      gpgcheck: true
      gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    become: true

  - name: Install VS Code
    become: true
    dnf:
      name: "code{{ (visual_studio_code_version != '') | ternary('=' + visual_studio_code_version, '') }}"
      state: present
  when: ansible_distribution == 'Fedora'
