---
- name: Ubuntu | Install Chrome
  block:
  - name: Ensure Google chrome keyring present
    shell: |
      set -o pipefail
      curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg
    args:
      creates: /usr/share/keyrings/google-chrome.gpg
    become: true

  - name: Ensure Google chrome repo present
    apt_repository:
      repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main"
      filename: "google-chrome"
      state: present
      update_cache: yes
    become: true

  - name: Install Google Chrome
    apt:
      name: "{{ chrome_package }}"
      state: present
    become: true
  when: ansible_distribution in ["Ubuntu", "Pop!_OS", "Linux Mint"]

- name: Fedora | Install Chrome
  block:
  - name: Ensure Google linux signing key present
    yum_repository:
      name: google-chrome
      description: "Google Chrome"
      baseurl: "{{ fedora_chrome_baseurl }}"
      enabled: yes
      gpgcheck: yes
      gpgkey: "{{ fedora_chrome_key_url }}"
    become: true

  - name: Install Google Chrome
    dnf:
      name: "{{ chrome_package }}"
      state: present
    become: true
  when: ansible_distribution == 'Fedora'
