---

- name: check if dotnet sdk is installed
  shell: which dotnet
  register: dotnet_installed
  ignore_errors: true

- include_tasks: ubuntu.yml
  when:
    - ansible_distribution in ["Ubuntu", "Pop!_OS", "Linux Mint"]
    - not snap_dotnet_install | bool

- include_tasks: fedora.yml
  when:
    - ansible_distribution == 'Fedora'
    - not snap_dotnet_install | bool

- name: install Dotnet sdk from snap
  snap:
    name: "dotnet-sdk"
    classic: yes
  become: true
  when:
    - snap_dotnet_install | bool
    - dotnet_installed.rc == 1
