---

- include_tasks: ubuntu.yml
  when: ansible_distribution in ["Ubuntu", "Pop!_OS", "Linux Mint"]

- include_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'

- name: adding existing user '{{ ansible_user_id }}' to group docker
  user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: yes
  become: true

- name: Enable docker service
  systemd:
    name: docker
    enabled: yes
    masked: no
    state: reloaded
  become: true
