---
# Visual Studio Code version number (defaults to the latest version)
visual_studio_code_version: ''

fedora_dependencies:
  - ca-certificates

ubuntu_dependencies:
  - ca-certificates
  - apt-transport-https

